/*
 * This file is generated by jOOQ.
 */
package com.appointement.app.custoapp.db;


import com.appointement.app.custoapp.db.tables.Appointment;
import com.appointement.app.custoapp.db.tables.records.AppointmentRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppointmentRecord> APPOINTMENT_PKEY = UniqueKeys0.APPOINTMENT_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AppointmentRecord> APPOINTMENT_PKEY = Internal.createUniqueKey(Appointment.APPOINTMENT, "appointment_pkey", new TableField[] { Appointment.APPOINTMENT.ID }, true);
    }
}
