/*
 * This file is generated by jOOQ.
 */
package com.appointement.app.custoapp.db;


import com.appointement.app.custoapp.db.tables.Appointment;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.appointment</code>.
     */
    public static final Appointment APPOINTMENT = Appointment.APPOINTMENT;
}
