/*
 * This file is generated by jOOQ.
 */
package com.appointement.app.custoapp.db.tables.records;


import com.appointement.app.custoapp.db.tables.Appointment;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppointmentRecord extends UpdatableRecordImpl<AppointmentRecord> implements Record9<UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, String, String, String, String> {

    private static final long serialVersionUID = 468302660;

    /**
     * Setter for <code>public.appointment.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.appointment.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.appointment.start_datetime_at</code>.
     */
    public void setStartDatetimeAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.appointment.start_datetime_at</code>.
     */
    public OffsetDateTime getStartDatetimeAt() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.appointment.end_datetime_at</code>.
     */
    public void setEndDatetimeAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.appointment.end_datetime_at</code>.
     */
    public OffsetDateTime getEndDatetimeAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.appointment.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.appointment.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.appointment.user_email</code>.
     */
    public void setUserEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.appointment.user_email</code>.
     */
    public String getUserEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.appointment.user_phone</code>.
     */
    public void setUserPhone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.appointment.user_phone</code>.
     */
    public String getUserPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.appointment.services</code>.
     */
    public void setServices(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.appointment.services</code>.
     */
    public String getServices() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.appointment.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.appointment.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.appointment.place</code>.
     */
    public void setPlace(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.appointment.place</code>.
     */
    public String getPlace() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, String, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, String, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Appointment.APPOINTMENT.ID;
    }

    @Override
    public Field<OffsetDateTime> field2() {
        return Appointment.APPOINTMENT.START_DATETIME_AT;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return Appointment.APPOINTMENT.END_DATETIME_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Appointment.APPOINTMENT.CREATED_AT;
    }

    @Override
    public Field<String> field5() {
        return Appointment.APPOINTMENT.USER_EMAIL;
    }

    @Override
    public Field<String> field6() {
        return Appointment.APPOINTMENT.USER_PHONE;
    }

    @Override
    public Field<String> field7() {
        return Appointment.APPOINTMENT.SERVICES;
    }

    @Override
    public Field<String> field8() {
        return Appointment.APPOINTMENT.STATUS;
    }

    @Override
    public Field<String> field9() {
        return Appointment.APPOINTMENT.PLACE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public OffsetDateTime component2() {
        return getStartDatetimeAt();
    }

    @Override
    public OffsetDateTime component3() {
        return getEndDatetimeAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public String component5() {
        return getUserEmail();
    }

    @Override
    public String component6() {
        return getUserPhone();
    }

    @Override
    public String component7() {
        return getServices();
    }

    @Override
    public String component8() {
        return getStatus();
    }

    @Override
    public String component9() {
        return getPlace();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public OffsetDateTime value2() {
        return getStartDatetimeAt();
    }

    @Override
    public OffsetDateTime value3() {
        return getEndDatetimeAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public String value5() {
        return getUserEmail();
    }

    @Override
    public String value6() {
        return getUserPhone();
    }

    @Override
    public String value7() {
        return getServices();
    }

    @Override
    public String value8() {
        return getStatus();
    }

    @Override
    public String value9() {
        return getPlace();
    }

    @Override
    public AppointmentRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public AppointmentRecord value2(OffsetDateTime value) {
        setStartDatetimeAt(value);
        return this;
    }

    @Override
    public AppointmentRecord value3(OffsetDateTime value) {
        setEndDatetimeAt(value);
        return this;
    }

    @Override
    public AppointmentRecord value4(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AppointmentRecord value5(String value) {
        setUserEmail(value);
        return this;
    }

    @Override
    public AppointmentRecord value6(String value) {
        setUserPhone(value);
        return this;
    }

    @Override
    public AppointmentRecord value7(String value) {
        setServices(value);
        return this;
    }

    @Override
    public AppointmentRecord value8(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public AppointmentRecord value9(String value) {
        setPlace(value);
        return this;
    }

    @Override
    public AppointmentRecord values(UUID value1, OffsetDateTime value2, OffsetDateTime value3, OffsetDateTime value4, String value5, String value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppointmentRecord
     */
    public AppointmentRecord() {
        super(Appointment.APPOINTMENT);
    }

    /**
     * Create a detached, initialised AppointmentRecord
     */
    public AppointmentRecord(UUID id, OffsetDateTime startDatetimeAt, OffsetDateTime endDatetimeAt, OffsetDateTime createdAt, String userEmail, String userPhone, String services, String status, String place) {
        super(Appointment.APPOINTMENT);

        set(0, id);
        set(1, startDatetimeAt);
        set(2, endDatetimeAt);
        set(3, createdAt);
        set(4, userEmail);
        set(5, userPhone);
        set(6, services);
        set(7, status);
        set(8, place);
    }
}
